# Generated by Django 6.0.3 on 2026-03-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardedGSTIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('trade_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTINFilingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('GSTR9', 'GSTR-9')], max_length=10)),
                ('period', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Filed', 'Filed'), ('Not Filed', 'Not Filed'), ('Pending', 'Pending')], max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filing_statuses', to='gst_data.onboardedgstin')),
            ],
            options={
                'unique_together': {('gstin', 'return_type', 'period')},
            },
        ),
    ]
