# Generated by Django 6.0.3 on 2026-03-04 13:55

from django.db import migrations
import datetime


GSTINS = [
    {
        'gstin': '27AABCU9603R1ZX',
        'trade_name': 'Acme Traders',
        'legal_name': 'Acme Traders Pvt Ltd',
        'state': 'Maharashtra',
        'is_active': True,
    },
    {
        'gstin': '07AABCU9603R2ZY',
        'trade_name': 'Delhi Enterprises',
        'legal_name': 'Delhi Enterprises LLP',
        'state': 'Delhi',
        'is_active': True,
    },
    {
        'gstin': '29AABCU9603R3ZZ',
        'trade_name': 'Karnataka Supplies',
        'legal_name': 'Karnataka Supplies Pvt Ltd',
        'state': 'Karnataka',
        'is_active': True,
    },
    {
        'gstin': '33AABCU9603R4ZW',
        'trade_name': 'Tamil Goods Co',
        'legal_name': 'Tamil Goods Company Ltd',
        'state': 'Tamil Nadu',
        'is_active': False,
    },
]

# (period, due_date_gstr1, due_date_gstr3b)
PERIODS = [
    ('Dec-2025', datetime.date(2026, 1, 11), datetime.date(2026, 1, 20)),
    ('Jan-2026', datetime.date(2026, 2, 11), datetime.date(2026, 2, 20)),
    ('Feb-2026', datetime.date(2026, 3, 11), datetime.date(2026, 3, 20)),
]

# (gstin_index, return_type, period_index, status, filed_date)
FILING_DATA = [
    (0, 'GSTR1',  0, 'Filed',     datetime.date(2026, 1, 9)),
    (0, 'GSTR3B', 0, 'Filed',     datetime.date(2026, 1, 18)),
    (0, 'GSTR1',  1, 'Filed',     datetime.date(2026, 2, 10)),
    (0, 'GSTR3B', 1, 'Pending',   None),
    (0, 'GSTR1',  2, 'Not Filed', None),
    (0, 'GSTR3B', 2, 'Not Filed', None),

    (1, 'GSTR1',  0, 'Filed',     datetime.date(2026, 1, 10)),
    (1, 'GSTR3B', 0, 'Filed',     datetime.date(2026, 1, 19)),
    (1, 'GSTR1',  1, 'Not Filed', None),
    (1, 'GSTR3B', 1, 'Not Filed', None),
    (1, 'GSTR1',  2, 'Not Filed', None),
    (1, 'GSTR3B', 2, 'Not Filed', None),

    (2, 'GSTR1',  0, 'Filed',     datetime.date(2026, 1, 8)),
    (2, 'GSTR3B', 0, 'Filed',     datetime.date(2026, 1, 17)),
    (2, 'GSTR1',  1, 'Filed',     datetime.date(2026, 2, 9)),
    (2, 'GSTR3B', 1, 'Filed',     datetime.date(2026, 2, 18)),
    (2, 'GSTR1',  2, 'Pending',   None),
    (2, 'GSTR3B', 2, 'Not Filed', None),

    (3, 'GSTR1',  0, 'Filed',     datetime.date(2026, 1, 11)),
    (3, 'GSTR3B', 0, 'Filed',     datetime.date(2026, 1, 20)),
    (3, 'GSTR1',  1, 'Not Filed', None),
    (3, 'GSTR3B', 1, 'Not Filed', None),
]


def seed(apps, schema_editor):
    OnboardedGSTIN = apps.get_model('gst_data', 'OnboardedGSTIN')
    GSTINFilingStatus = apps.get_model('gst_data', 'GSTINFilingStatus')

    gstin_objs = []
    for data in GSTINS:
        obj = OnboardedGSTIN.objects.create(**data)
        gstin_objs.append(obj)

    for gstin_idx, return_type, period_idx, status, filed_date in FILING_DATA:
        period, due_gstr1, due_gstr3b = PERIODS[period_idx]
        due_date = due_gstr1 if return_type == 'GSTR1' else due_gstr3b
        GSTINFilingStatus.objects.create(
            gstin=gstin_objs[gstin_idx],
            return_type=return_type,
            period=period,
            status=status,
            filed_date=filed_date,
            due_date=due_date,
        )


def unseed(apps, schema_editor):
    OnboardedGSTIN = apps.get_model('gst_data', 'OnboardedGSTIN')
    OnboardedGSTIN.objects.filter(
        gstin__in=[g['gstin'] for g in GSTINS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gst_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
