# Generated by Django 6.0.3 on 2026-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_data', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardedgstin',
            name='admin_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
