# Generated by Django 6.0.3 on 2026-03-04 14:04

from django.db import migrations

EMAIL_MAP = {
    '27AABCU9603R1ZX': 'admin@acmetraders.com',
    '07AABCU9603R2ZY': 'admin@delhienterprises.com',
    '29AABCU9603R3ZZ': 'admin@karnatakasupp.com',
    '33AABCU9603R4ZW': 'admin@tamilgoods.com',
}


def seed_emails(apps, schema_editor):
    OnboardedGSTIN = apps.get_model('gst_data', 'OnboardedGSTIN')
    for gstin, email in EMAIL_MAP.items():
        OnboardedGSTIN.objects.filter(gstin=gstin).update(admin_email=email)


class Migration(migrations.Migration):

    dependencies = [
        ('gst_data', '0003_add_admin_email'),
    ]

    operations = [
        migrations.RunPython(seed_emails, migrations.RunPython.noop),
    ]
