# Generated by Django 6.0.3 on 2026-03-04 15:47

from django.db import migrations
import datetime

# Periods for FY 2024-25 (Apr-2024 to Mar-2025)
FY2425_PERIODS = [
    ('Apr-2024', datetime.date(2024, 5, 11), datetime.date(2024, 5, 20)),
    ('Jul-2024', datetime.date(2024, 8, 11), datetime.date(2024, 8, 20)),
    ('Oct-2024', datetime.date(2024, 11, 11), datetime.date(2024, 11, 20)),
    ('Jan-2025', datetime.date(2025, 2, 11), datetime.date(2025, 2, 20)),
    ('Mar-2025', datetime.date(2025, 4, 11), datetime.date(2025, 4, 20)),
]

# Periods for FY 2025-26 (existing + new)
FY2526_EXTRA_PERIODS = [
    ('Apr-2025', datetime.date(2025, 5, 11), datetime.date(2025, 5, 20)),
    ('Jul-2025', datetime.date(2025, 8, 11), datetime.date(2025, 8, 20)),
    ('Oct-2025', datetime.date(2025, 11, 11), datetime.date(2025, 11, 20)),
]

# Existing periods (already seeded in 0002)
EXISTING_PERIODS = ['Dec-2025', 'Jan-2026', 'Feb-2026']

# (gstin_index, return_type, period_index, status, filed_date)
# gstin indices: 0=MH, 1=DL, 2=KA, 3=TN(inactive)

FY2425_FILING = [
    # Apr-2024
    (0, 'GSTR1',  0, 'Filed',     datetime.date(2024, 5, 9)),
    (0, 'GSTR3B', 0, 'Filed',     datetime.date(2024, 5, 18)),
    (1, 'GSTR1',  0, 'Filed',     datetime.date(2024, 5, 10)),
    (1, 'GSTR3B', 0, 'Filed',     datetime.date(2024, 5, 19)),
    (2, 'GSTR1',  0, 'Filed',     datetime.date(2024, 5, 8)),
    (2, 'GSTR3B', 0, 'Filed',     datetime.date(2024, 5, 17)),
    (3, 'GSTR1',  0, 'Not Filed', None),
    (3, 'GSTR3B', 0, 'Not Filed', None),
    # Jul-2024
    (0, 'GSTR1',  1, 'Filed',     datetime.date(2024, 8, 9)),
    (0, 'GSTR3B', 1, 'Filed',     datetime.date(2024, 8, 18)),
    (1, 'GSTR1',  1, 'Not Filed', None),
    (1, 'GSTR3B', 1, 'Pending',   None),
    (2, 'GSTR1',  1, 'Filed',     datetime.date(2024, 8, 8)),
    (2, 'GSTR3B', 1, 'Filed',     datetime.date(2024, 8, 17)),
    (3, 'GSTR1',  1, 'Not Filed', None),
    (3, 'GSTR3B', 1, 'Not Filed', None),
    # Oct-2024
    (0, 'GSTR1',  2, 'Filed',     datetime.date(2024, 11, 9)),
    (0, 'GSTR3B', 2, 'Filed',     datetime.date(2024, 11, 18)),
    (1, 'GSTR1',  2, 'Filed',     datetime.date(2024, 11, 10)),
    (1, 'GSTR3B', 2, 'Not Filed', None),
    (2, 'GSTR1',  2, 'Filed',     datetime.date(2024, 11, 8)),
    (2, 'GSTR3B', 2, 'Filed',     datetime.date(2024, 11, 17)),
    (3, 'GSTR1',  2, 'Not Filed', None),
    (3, 'GSTR3B', 2, 'Not Filed', None),
    # Jan-2025
    (0, 'GSTR1',  3, 'Filed',     datetime.date(2025, 2, 9)),
    (0, 'GSTR3B', 3, 'Filed',     datetime.date(2025, 2, 18)),
    (1, 'GSTR1',  3, 'Filed',     datetime.date(2025, 2, 10)),
    (1, 'GSTR3B', 3, 'Filed',     datetime.date(2025, 2, 19)),
    (2, 'GSTR1',  3, 'Filed',     datetime.date(2025, 2, 8)),
    (2, 'GSTR3B', 3, 'Not Filed', None),
    (3, 'GSTR1',  3, 'Not Filed', None),
    (3, 'GSTR3B', 3, 'Not Filed', None),
    # Mar-2025
    (0, 'GSTR1',  4, 'Filed',     datetime.date(2025, 4, 9)),
    (0, 'GSTR3B', 4, 'Filed',     datetime.date(2025, 4, 18)),
    (1, 'GSTR1',  4, 'Not Filed', None),
    (1, 'GSTR3B', 4, 'Not Filed', None),
    (2, 'GSTR1',  4, 'Filed',     datetime.date(2025, 4, 8)),
    (2, 'GSTR3B', 4, 'Filed',     datetime.date(2025, 4, 17)),
    (3, 'GSTR1',  4, 'Not Filed', None),
    (3, 'GSTR3B', 4, 'Not Filed', None),
]

FY2526_EXTRA_FILING = [
    # Apr-2025
    (0, 'GSTR1',  0, 'Filed',     datetime.date(2025, 5, 9)),
    (0, 'GSTR3B', 0, 'Filed',     datetime.date(2025, 5, 18)),
    (1, 'GSTR1',  0, 'Filed',     datetime.date(2025, 5, 10)),
    (1, 'GSTR3B', 0, 'Filed',     datetime.date(2025, 5, 19)),
    (2, 'GSTR1',  0, 'Filed',     datetime.date(2025, 5, 8)),
    (2, 'GSTR3B', 0, 'Filed',     datetime.date(2025, 5, 17)),
    # Jul-2025
    (0, 'GSTR1',  1, 'Filed',     datetime.date(2025, 8, 9)),
    (0, 'GSTR3B', 1, 'Filed',     datetime.date(2025, 8, 18)),
    (1, 'GSTR1',  1, 'Pending',   None),
    (1, 'GSTR3B', 1, 'Not Filed', None),
    (2, 'GSTR1',  1, 'Filed',     datetime.date(2025, 8, 8)),
    (2, 'GSTR3B', 1, 'Filed',     datetime.date(2025, 8, 17)),
    # Oct-2025
    (0, 'GSTR1',  2, 'Filed',     datetime.date(2025, 11, 9)),
    (0, 'GSTR3B', 2, 'Filed',     datetime.date(2025, 11, 18)),
    (1, 'GSTR1',  2, 'Filed',     datetime.date(2025, 11, 10)),
    (1, 'GSTR3B', 2, 'Not Filed', None),
    (2, 'GSTR1',  2, 'Filed',     datetime.date(2025, 11, 8)),
    (2, 'GSTR3B', 2, 'Filed',     datetime.date(2025, 11, 17)),
]

# GSTR9 (annual) — one record per GSTIN per FY, use Mar period for annual
GSTR9_FILING = [
    # FY 2024-25 annual (filed in Dec 2025)
    (0, 'GSTR9', 'Mar-2025', 'Filed',     datetime.date(2025, 12, 15), datetime.date(2025, 12, 31)),
    (1, 'GSTR9', 'Mar-2025', 'Filed',     datetime.date(2025, 12, 20), datetime.date(2025, 12, 31)),
    (2, 'GSTR9', 'Mar-2025', 'Filed',     datetime.date(2025, 12, 18), datetime.date(2025, 12, 31)),
    (3, 'GSTR9', 'Mar-2025', 'Not Filed', None,                         datetime.date(2025, 12, 31)),
    # FY 2025-26 annual (pending)
    (0, 'GSTR9', 'Mar-2026', 'Pending',   None, datetime.date(2026, 12, 31)),
    (1, 'GSTR9', 'Mar-2026', 'Not Filed', None, datetime.date(2026, 12, 31)),
    (2, 'GSTR9', 'Mar-2026', 'Pending',   None, datetime.date(2026, 12, 31)),
    (3, 'GSTR9', 'Mar-2026', 'Not Filed', None, datetime.date(2026, 12, 31)),
]


def seed(apps, schema_editor):
    OnboardedGSTIN = apps.get_model('gst_data', 'OnboardedGSTIN')
    GSTINFilingStatus = apps.get_model('gst_data', 'GSTINFilingStatus')

    gstins = list(OnboardedGSTIN.objects.order_by('id'))

    # FY 2024-25 filings
    for gstin_idx, return_type, period_idx, status, filed_date in FY2425_FILING:
        period, due_gstr1, due_gstr3b = FY2425_PERIODS[period_idx]
        due_date = due_gstr1 if return_type == 'GSTR1' else due_gstr3b
        GSTINFilingStatus.objects.get_or_create(
            gstin=gstins[gstin_idx], return_type=return_type, period=period,
            defaults={'status': status, 'filed_date': filed_date, 'due_date': due_date}
        )

    # FY 2025-26 extra periods
    for gstin_idx, return_type, period_idx, status, filed_date in FY2526_EXTRA_FILING:
        period, due_gstr1, due_gstr3b = FY2526_EXTRA_PERIODS[period_idx]
        due_date = due_gstr1 if return_type == 'GSTR1' else due_gstr3b
        GSTINFilingStatus.objects.get_or_create(
            gstin=gstins[gstin_idx], return_type=return_type, period=period,
            defaults={'status': status, 'filed_date': filed_date, 'due_date': due_date}
        )

    # GSTR9 annual filings
    for gstin_idx, return_type, period, status, filed_date, due_date in GSTR9_FILING:
        GSTINFilingStatus.objects.get_or_create(
            gstin=gstins[gstin_idx], return_type=return_type, period=period,
            defaults={'status': status, 'filed_date': filed_date, 'due_date': due_date}
        )


def unseed(apps, schema_editor):
    GSTINFilingStatus = apps.get_model('gst_data', 'GSTINFilingStatus')
    periods = [p[0] for p in FY2425_PERIODS] + [p[0] for p in FY2526_EXTRA_PERIODS]
    GSTINFilingStatus.objects.filter(period__in=periods).delete()
    GSTINFilingStatus.objects.filter(return_type='GSTR9').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gst_data', '0004_seed_admin_email'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
